version: '3.1'

services:
  app:
    container_name: send_mail_app_1
    ports:
      - 8000:8000
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - common
    env_file:
      - .env
    environment:
      - ENV=PROD

networks:
  common:
     external: true