version: '3.1'

services:
  app:
    ports:
      - 8000:8000
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - common
    environment:
      - ENV=PROD

networks:
  common:
     external: true